# The recipe for
#   $ pdflatex in.tex
# under default styles (Computer Modern, article class)

[[heading]]
level = 1
greedy = true
font.name = "CMBX12"
font.size = 14.346199989318848
font.size_tolerance = 0.01

[[heading]]
level = 2
greedy = true
font.name = "CMBX12"
font.size = 11.9552001953125
font.size_tolerance = 0.01

[[heading]]
level = 3
greedy = true
font.name = "CMBX10"
font.size = 9.962599754333496
font.size_tolerance = 0.01
