[[filter]]
level = 1
font.name = "CMBX12"
font.size = 14.346199989318848
font.size_tolerance = 0.01
font.superscript = false
font.italic = false
font.serif = true
font.monospace = false
font.bold = true

[[filter]]
level = 2
font.name = "CMBX10"
font.size = 9.962599754333496
font.size_tolerance = 0.01
font.superscript = false
font.italic = false
font.serif = true
font.monospace = false
font.bold = true
