# The recipe for J.S. Milne's lecture notes on Group Theory [1]
#
# Only tested for version 3.16, July 16, 2020, some post-processing are needed
# to remove extraneous white spaces
#
# [1]: https://www.jmilne.org/math/CourseNotes/GT.pdf

[[filter]]
level = 1
font.name = "NimbusSanL-Bold"
font.size = 22.804000854492188

[[filter]]
level = 2
font.name = "(NimbusRomNo9L-Medi|MT2MIT)"
font.size = 14.346199989318848
