# The recipe for HtDC by Matthias Felleisen, et al.
#
# The output need some manual clean up. For example, the table of contents in
# the original document is incorrectedly included in the outline, but they
# should be easy to remove using a text editor.
#
# [1]: https://felleisen.org/matthias/HtDC/htdc.pdf

[[filter]]
level = 1
font.name = "Palatino-Bold"
font.size = 17.21540069580078
font.color = 0x221f1f

[[filter]]
level = 2
font.name = "Palatino-Bold"
font.size = 14.346199989318848
font.color = 0x221f1f

[[filter]]
level = 3
font.name = "(Palatino-Bold|Palatino-Italic)"
font.size = 11.9552001953125
font.color = 0x221f1f
